const URL_GENERATION_REQUEST = "URL_GENERATION_REQUEST";
const URL_GENERATION_SUCCESS = "URL_GENERATION_SUCCESS";
const URL_GENERATION_FAILED = "URL_GENERATION_FAILED";

const TINYURL_REQUEST = "TINYURL_REQUEST";
const TINYURL_SUCCESS = "TINYURL_SUCCESS";
const TINYURL_FAILED = "TINYURL_FAILED";

const NEW_REQUEST = "NEW_REQUEST";

const TOGGLE_DRAWER = "TOGGLE_DRAWER";

const SIGNUP_REQUEST = "SIGNUP_REQUEST";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_FAILED = "SIGNUP_FAILED";

const SIGNIN_REQUEST = "SIGNIN_REQUEST";
const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
const SIGNIN_FAILED = "SIGNIN_FAILED";

export {
  URL_GENERATION_REQUEST,
  URL_GENERATION_SUCCESS,
  URL_GENERATION_FAILED,
  TINYURL_REQUEST,
  TINYURL_SUCCESS,
  TINYURL_FAILED,
  NEW_REQUEST,
  TOGGLE_DRAWER,
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  SIGNUP_FAILED,
  SIGNIN_REQUEST,
  SIGNIN_SUCCESS,
  SIGNIN_FAILED,
};
