const URL_GENERATION_REQUEST = "URL_GENERATION_REQUEST";
const URL_GENERATION_SUCCESS = "URL_GENERATION_SUCCESS";
const URL_GENERATION_FAILED = "URL_GENERATION_FAILED";

const TINYURL_REQUEST = "TINYURL_REQUEST";
const TINYURL_SUCCESS = "TINYURL_SUCCESS";
const TINYURL_FAILED = "TINYURL_FAILED";

const NEW_REQUEST = "NEW_REQUEST";

export {
  URL_GENERATION_REQUEST,
  URL_GENERATION_SUCCESS,
  URL_GENERATION_FAILED,
  TINYURL_REQUEST,
  TINYURL_SUCCESS,
  TINYURL_FAILED,
  NEW_REQUEST,
};
